window.paperAuthorsByTitle = {
  "Ghost Talk: Mitigating EMI Signal Injection Attacks Against Analog Sensors": "D. F. Kune, J. Backes, S. S. Clark, D. Kramer, M. Reynolds, K. Fu, Yongdae Kim, Wenyuan Xu",
  "Prediction and Root-Cause Analysis for Smart Speaker Intentional Electromagnetic Interference Attacks": "Tanner Fokkens, Shengxuan Xia, Aaron Harmon, Chulsoon Hwang",
  "IEMI Threats for Information Security: Remote Command Injection on Modern Smartphones": "Chaouki Kasmi, Jose Lopes Esteves",
  "Inducing Wireless Chargers to Voice Out for Inaudible Command Attacks": "Donghui Dai, Zhenlin An, Lei Yang",
  "Remote and Silent Voice Command Injection on a Smartphone Through Conducted IEMI": "Payton Walker, Tianfang Zhang, Cong Shi, Nitesh Saxena, Yingying Chen",
  "PowerRadio: Manipulate Sensor Measurement via Power GND Radiation": "Yan Jiang, Xiaoyu Ji, Yancheng Jiang, Kai Wang, Chenren Xu, Wenyuan Xu",
  "Tap'n Ghost: A Compilation of Novel Attack Techniques Against Smartphone Touchscreens": "Seita Maruyama, Satohiro Wakabayashi, Tatsuya Mori",
  "Expelliarmus: Command Cancellation Attacks on Smartphones Using Electromagnetic Interference": "Ming Gao, Fu Xiao, Weiran Liu, Wentao Guo, Yangtao Huang, Yajie Liu, Jinsong Han",
  "Invisible Finger: Practical Electromagnetic Interference Attack on Touchscreen-based Electronic Devices": "Haoqi Shan, Boyi Zhang, Zihao Zhan, Dean Sullivan, Shuo Wang, Yier Jin",
  "GhostTouch: Targeted Attacks on Touchscreens Without Physical Touch": "Yan Jiang, Xiaoyu Ji, Kai Wang, Chen Yan, Richard Mitev, Ahmad-Reza Sadeghi, Wenyuan Xu",
  "Wight: Wired Ghost Touch Attack on Capacitive Touchscreens": "Yan Jiang, Xiaoyu Ji, Kai Wang, Chen Yan, Richard Mitev, Ahmad-Reza Sadeghi, Wenyuan Xu",
  "PowerTouch: A Security Objective-Guided Automation Framework for Generating Wired Ghost Touch Attacks on Touchscreens": "Yan Jiang, Xiaoyu Ji, Kai Wang, Chen Yan, Richard Mitev, Ahmad-Reza Sadeghi, Wenyuan Xu",
  "Digital Camera Detection and Image Disruption Using Controlled Intentional Electromagnetic Interference": "A. Schwarz, Y. Sanhedrai, Z. Zalevsky",
  "Magcode: NFC-enabled Barcodes for NFC-Disabled Smartphones": "Donghui Dai, Zhenlin An, Qingrui Pan, Lei Yang",
  "MagShadow: Physical Adversarial Example Attacks via Electromagnetic Injection": "Ziwei Liu, Feng Lin, Zhongjie Ba, Li Lu, Kui Ren",
  "GlitchHiker: Uncovering Vulnerabilities of Image Signal Transmission with IEMI": "Yi Liang, Yi Hu, Daohong Song, Cibo Lou, Xinzheng Zhang, Zhigang Chen, Jingjun Xu",
  "From Virtual Touch to Tesla Command: Unlocking Unauthenticated Control Chains From Smart Glasses for Vehicle Takeover": "Xingli Zhang, Yazhou Tu, Yan Long, Liqun Shan, Mohamed A Elsaadani, Kevin Fu, Zhiqiang Lin, Xiali Hei",
  "Towards Wireless Spiking of Smart Locks": "Abdullah Z Mohammed, Alok Singh, Gokcen Y Dayanikli, Ryan Gerdes, Mani Mina, Ming Li",
  "Inaudible Attack on Smart Speakers With Intentional Electromagnetic Interference": "Zhifei Xu, Runbing Hua, Jack Juang, Shengxuan Xia, Jun Fan, Chulsoon Hwang",
  "Magbackdoor: Beware of Your Loudspeaker as a Backdoor for Magnetic Injection Attacks": "Tiantian Liu, Feng Lin, Zhangsen Wang, Chao Wang, Zhongjie Ba, Li Lu, Wenyao Xu, Kui Ren",
  "EMI-LiDAR: Uncovering Vulnerabilities of LiDAR Sensors in Autonomous Driving Setting Using Electromagnetic Interference": "Sri Hrushikesh Varma Bhupathiraju, Jennifer Sheldon, Luke A. Bauer, Vincent Bindschaedler, Takeshi Sugawara, Sara Rampazzi",
  "PhantomLiDAR: Cross-modality Signal Injection Attacks against LiDAR": "Zizhi Jin, Qinhong Jiang, Xuancun Lu, Chen Yan, Xiaoyu Ji, Wenyuan Xu",
  "EMTrig: Physical Adversarial Examples Triggered by Electromagnetic Injection towards LiDAR Perception": "Ziwei Liu, Feng Lin, Teshi Meng, Benaouda Chouaib Baha-eddine, Li Lu, Qiang Xue, Kui Ren",
  "Non-Invasive Spoofing Attacks for Anti-lock Braking Systems": "Yasser Shoukry, Paul Martin, Paulo Tabuada, Mani Srivastava",
  "Review of Intentional Electromagnetic Interference on UAV Sensor Modules": "Sung-Geon Kim, Euibum Lee, Ic-Pyo Hong, Jong-Gwan Yook",
  "Paralyzing Drones via EMI Signal Injection on Sensory Communication Channels": "Joonha Jang, ManGi Cho, Jaehoon Kim, Dongkwan Kim, Yongdae Kim",
  "One Shot All Kill: Building Optimal Attack on Swarm Drones": "Minki Lee, GangMin Kim, JongHyun Kang, Hyunwoo Kim, Jangwon Lee, Hongjun Choi",
  "ConfuSense: Sensor Reconfiguration Attacks for Stealthy UAV Manipulation": "Paul J Bonczek, Nicola Bezzo",
  "Electromagnetic Interference Attacks on Cyber-Physical Systems: Theory, Demonstration, and Defense": "Qingyu Su, Handong Wang, Chaowei Sun, Bo Li, Jian Li",
  "Physical-Layer Attacks Against Pulse Width Modulation-Controlled Actuators": "S.P. Gladyshev, P.S. Gladyshev, I.S. Okrainskaya, N. P. Gladychev",
  "A First Look at the Security of EEG-based Systems and Intelligent Algorithms under Physical Signal Injections": "Md Imran Hossen, Yazhou Tu, Xiali Hei",
  "Brain-Hack: Remotely Injecting False Brain-Waves with RF to Take Control of a Brain-Computer Interface": "Alexandre Armengol-Urpi, Reid Kovacs, Sanjay E. Sarma",
  "Trick or Heat?: Manipulating Critical Temperature-Based Control Systems Using Rectification Attacks": "Istvan Kiss, Bela Genge, Piroska Haller",
  "ReThink: Reveal the Threat of Electromagnetic Interference on Power Inverters": "Fengchen Yang, Zihao Dan, Kaikai Pan, Chen Yan, Xiaoyu Ji, Wenyuan Xu",
  "Hall Spoofing: A Non-Invasive DoS Attack on Grid-Tied Solar Inverter": "Tai-Hung Wang, Yu-Chen Liu, Shih-Jen Cheng, Yu-Kang Lo, Huang-Jen Chiu",
  "Assault and Battery: Evaluating the Security of Power Conversion Systems Against Electromagnetic Injection Attacks": "Marcell Szakály, Sebastian Köhler, Martin Strohmeier, Ivan Martinovic",
  "Signal Injection Attacks against CCD Image Sensors": "Sebastian Köhler, Richard Baker, Ivan Martinovic",
  "Unlocking the Access to the Effects Induced By IEMI on a Civilian UAV": "Jose Lopes Esteves, Emmanuel Cottais, Chaouki Kasmi",
  "VoltTack: Control IoT Devices by Manipulating Power Supply Voltage": "Kai Wang, Shilin Xiao, Xiaoyu Ji, Chen Yan, Chaohao Li, Wenyuan Xu",
  "Electromagnetic Sensor and Actuator Attacks on Power Converters for Electric Vehicles": "Gokcen Yilmaz Dayanikli, Rees R. Hatch, Ryan M. Gerdes, Hongjie Wang, Regan Zane",
  "BrokenWire: Wireless Disruption of CCS Electric Vehicle Charging": "Sebastian Köhler, Richard Baker, Martin Strohmeier, Ivan Martinovic",
  "Securing EV Charging System against Physical-layer Signal Injection Attack": "Soyeon Son, Kyungho Joo, Wonsuk Choi, Dong Hoon Lee",
  "Short: Breaking the Charge: Exploiting State Manipulation in EV Charging": "Pradeep Kumar Mallaiah, Nazmus Saqib, Shaurya Purohit, Manimaran Govindarasu",
  "GhostType: The Limits of Using Contactless Electromagnetic Interference to Inject Phantom Keys into Analog Circuits of Keyboards": "Qinhong Jiang, Yanze Ren, Yan Long, Chen Yan, Yumai Sun, Xiaoyu Ji, Kevin Fu, Wenyuan Xu",
  "PuppetMouse: Practical and Contactless Mouse Manipulation Attack via Intentional Electromagnetic Interference Injection": "Wenfan Song, Jianwei Liu, Jinsong Han",
  "On Disruption of Wired Serial Communication Links by Time Domain Interference": "M. J. Basford, C. Smartt, D. W. P. Thomas, S. Greedy",
  "BitDance: Manipulating UART Serial Communication with IEMI": "Zhixin Xie, Chen Yan, Xiaoyu Ji, Wenyuan Xu",
  "Wireless Manipulation of Serial Communication": "Gökçen Yılmaz Dayanıklı, Abdullah Zubair Mohammed, Ryan Gerdes, Mani Mina",
  "Electromagnetic Signal Injection Attacks on Differential Signaling": "Youqian Zhang, Kasper Rasmussen",
  "Data Links Modelling under Radiated EMI and Its Impact on Sampling Errors in the Physical Layer": "A. E. Pena-Quintal, M. J. Basford, K. Niewiadomski, S. Greedy, M. Sumner, D. W. P. Thomas",
  "The Influence of Electromagnetic Disturbances on Data Transmission in USB Standard": "Michał Maćkowski",
  "Electrical Falsification of CAN Data by Magnetic Coupling": "David Dickson",
  "Intentional Electromagnetic Interference (IEMI) and Its Impact on the US Power Grid": "W.A. Radasky, M.W. Wik",
  "Event Logs Generated by an Operating System Running on a COTS Computer During IEMI Exposure": "C. Kasmi, J. Lopes-Esteves, N. Picard, M. Renard, B. Beillard, E. Martinod, J. Andrieu, M. Lalande"
};
